name: DropHeads
main: net.evmodder.DropHeads.DropHeads
author: EvModder/EvDoc
description: Provides a wide assortment of mob heads
website: https://dev.bukkit.org/projects/dropheads
#3=major rewrite, 3=VehicleDestroy+Broadcast, 9=added grumms, collared dogs, listener priority
version: 3.3.9
api-version: 1.13
softdepend: [HeadDatabase]

commands:
  spawnhead:
    description: Get a player or mob head
    usage: /gethead [name]
    aliases: [gethead,getskull,dhspawn,spawn-head,head,phspawn,skull]
    permission: dropheads.spawn
    permission-message: You do not have permission to do this.

  droprate:
    description: Check the drop rate for a head
    usage: /droprate <mob type>
    aliases: [headrate,headdropchance,dhrate,headchance]
    permission: dropheads.droprate
    permission-message: You do not have permission to do this.

  debug_all_heads:
    description: Place all heads into the world around the player
    usage: /debug_all_heads
    permission: dropheads.debug
    permission-message: You do not have permission to do this.

permissions:
  dropheads.canlosehead:
    description: Killing this entity can cause their head to drop
    default: true

  dropheads.canbehead:
    description: This entity will be able to get heads
    default: true

  dropheads.alwaysbehead:
    description: This entity will get heads 100% of the time, unless canlosehead is false
    default: false
    children:
      dropheads.canbehead: true

  dropheads.clickinfo:
    description: Permission to see info about a head by clicking it
    default: true

  dropheads.spawn:
    description: Permission to spawn heads with a command
    default: op

  dropheads.droprate:
    description: Permission to check head drop rates with a command
    default: op

  dropheads.debug:
    description: Permission to spawn all the heads in a big cube
    default: false