name: DropHeads
main: net.evmodder.DropHeads.DropHeads
author: EvModder/EvDoc
description: Provides a wide assortment of mob heads
website: https://dev.bukkit.org/projects/dropheads
#3=major rewrite
#6=translations, hex colors, wskele helmet drops, [item display], item display name rewrite, 1.17 mobs
#14=gethead <selector> <selector>,fix "player-heads-only" bug, add screaming|goat|grumm & magma_cube|lava_inside|grumm, screaming ghast head bugfix
version: 3.6.14
api-version: 1.13
softdepend: [HeadDatabase, Essentials, VanishNoPacket]

commands:
  spawnhead:
    description: Get a player or mob head
    usage: /gethead [giveto] [target] [amount]
    aliases: [gethead,givehead,getskull,giveskull,dhspawn,phspawn,head,skull]
    permission: dropheads.spawn
    permission-message: You do not have permission to do this.

  droprate:
    description: Check the drop rate for a head
    usage: /droprate <mob type>
    aliases: [headrate,headdropchance,dhrate,headchance]
    permission: dropheads.droprate
    permission-message: You do not have permission to do this.

  debug_all_heads:
    description: Place all heads into the world around the player
    usage: /debug_all_heads
    permission: dropheads.debug
    permission-message: You do not have permission to do this.

permissions:
  dropheads.canlosehead:
    description: Killing this entity can cause their head to drop
    default: true

  dropheads.canbehead:
    description: This entity will be able to get heads
    default: true

  dropheads.canplacehead:
    description: Permission to place down a head block, if disabled by default in the config
    default: op

  dropheads.clickinfo:
    description: Permission to see info about a head by clicking it
    default: true
    children:
      dropheads.clickinfo.mobs: true
      dropheads.clickinfo.players: true
      dropheads.clickinfo.hdb: true
#     dropheads.clickinfo.unknown: true

  dropheads.clickinfo.mobs:
    description: Permission to see info about a mob head by clicking it
    default: false

  dropheads.clickinfo.players:
    description: Permission to see info about a player head by clicking it
    default: false

  dropheads.clickinfo.hdb:
    description: Permission to see info about a HeadDatabase head by clicking it
    default: false

  dropheads.clickinfo.unknown:
    description: Permission to see info about an unknown type head by clicking it
    default: false

  dropheads.spawn:
    description: Permission to use /spawnhead
    default: op
    children:
      dropheads.spawn.mobs: true
      dropheads.spawn.players: true
      dropheads.spawn.self: true
      dropheads.spawn.code: true
      dropheads.spawn.hdb: true
      dropheads.spawn.give: true

  dropheads.spawn.mobs:
    description: Permission to spawn in mob heads
    default: false

  dropheads.spawn.players:
    description: Permission to spawn in other players' heads
    default: false

  dropheads.spawn.self:
    description: Permission to spawn in your own head
    default: false

  dropheads.spawn.code:
    description: Permission to spawn in heads with custom texture codes
    default: false

  dropheads.spawn.hdb:
    description: Permission to spawn in HeadDatabase heads
    default: false

  dropheads.spawn.give:
    description: Permission to spawn heads in other players' inventories
    default: false

  dropheads.droprate:
    description: Permission to check head drop rates with a command
    default: op

  dropheads.debug:
    description: Permission to spawn all the heads in a big cube
    default: false

  dropheads.alwaysbehead:
    description: This entity will get heads 100% of the time, unless canlosehead is false
    default: false
    children:
      dropheads.canbehead: true

  dropheads.silentbehead:
    description: Permission to hide all behead messages caused by this entity
    default: false
    children:
      dropheads.silentbehead.vanished: true
      dropheads.silentbehead.invisible: true

  dropheads.silentbehead.vanished:  # NOTE: Currently only supports Essentials and VanishNoPacket
    description: Permission to suppress the behead message while vanished
    default: true

  dropheads.silentbehead.invisible:
    description: Permission to suppress the behead message while invisible
    default: true
